import keyMirror from 'fbjs/lib/keyMirror'

export default keyMirror({
  RECEIVE_MEMBERLIST_START: null,
  RECEIVE_MEMBERLIST_SUCCESS: null,
  RECEIVE_MEMBERLIST_FAILURE: null,
  RECEIVE_MEMBER_START: null,
  RECEIVE_MEMBER_SUCCESS: null,
  RECEIVE_MEMBER_FAILURE: null,
  RECEIVE_MEMBERSEARCH_START: null,
  RECEIVE_MEMBERSEARCH_SUCCESS: null,
  RECEIVE_MEMBERSEARCH_FAILURE: null,
  RECEIVE_MEMBERSTATS_START: null,
  RECEIVE_MEMBERSTATS_SUCCESS: null,
  RECEIVE_MEMBERSTATS_FAILURE: null,
  MEMBER_DELETED: null,
  MEMBER_UPDATED: null,
})
