import keyMirror from 'fbjs/lib/keyMirror'

export default keyMirror({
    RECIVE_MEMBERLIST_START: null,
    RECIVE_MEMBERLIST_SUCCESS: null,
    RECIVE_MEMBERLIST_FAILURE: null,
    RECIVE_MEMBER_START: null,
    RECIVE_MEMBER_SUCCESS: null,
    RECIVE_MEMBER_FAILURE: null,
    RECIVE_MEMBERSEARCH_START: null,
    RECIVE_MEMBERSEARCH_SUCCESS: null,
    RECIVE_MEMBERSEARCH_FAILURE: null,
  RECIVE_MEMBERSTATS_START: null,
  RECIVE_MEMBERSTATS_SUCCESS: null,
  RECIVE_MEMBERSTATS_FAILURE: null,
    MEMBER_DELETED: null,
    MEMBER_UPDATED: null,
})
