import keyMirror from 'fbjs/lib/keyMirror'

export default keyMirror({
  RECEIVE_STATS_START: null,
  RECEIVE_STATS_SUCCESS: null,
  RECEIVE_STATS_FAILURE: null,
  RECEIVE_USELOGS_START: null,
  RECEIVE_USELOGS_SUCCESS: null,
  RECEIVE_USELOGS_FAILURE: null,
  RECEIVE_WALLETS_START: null,
  RECEIVE_WALLETS_SUCCESS: null,
  RECEIVE_WALLETS_FAILURE: null,
  RECEIVE_WORKLOGS_START: null,
  RECEIVE_WORKLOGS_SUCCESS: null,
  RECEIVE_WORKLOGS_FAILURE: null,
  SET_ACTIVE_SEMESTER: null,
  WORKLOG_UPDATED: null,
  WORKLOG_DELETED: null,
})
