import keyMirror from "fbjs/lib/keyMirror"

export default keyMirror({
  RECEIVE_INVENTORYITEMS_START: null,
  RECEIVE_INVENTORYITEMS_SUCCESS: null,
  RECEIVE_INVENTORYITEMS_FAILURE: null,
  INVENTORYITEMS_FILTERS: null,
  INVENTORYITEMS_FILTERS_CLEAR: null,
})
