import keyMirror from 'fbjs/lib/keyMirror'

export default keyMirror({
  RECEIVE_INTERNLIST_START: null,
  RECEIVE_INTERNLIST_SUCCESS: null,
  RECEIVE_INTERNLIST_FAILURE: null,
  RECEIVE_GROUPLIST_START: null,
  RECEIVE_GROUPLIST_SUCCESS: null,
  RECEIVE_GROUPLIST_FAILURE: null,
  RECEIVE_ACCESS_LEVELS_START: null,
  RECEIVE_ACCESS_LEVELS_SUCCESS: null,
  RECEIVE_ACCESS_LEVELS_FAILURE: null,
  RECEIVE_INTERN_START: null,
  RECEIVE_INTERN_SUCCESS: null,
  RECEIVE_INTERN_FAILURE: null
})
