import keyMirror from 'fbjs/lib/keyMirror'

export default keyMirror({
  RECEIVE_INTERNLIST_START: null,
  RECEIVE_INTERNLIST_SUCCESS: null,
  RECEIVE_INTERNLIST_FAILURE: null,
  RECEIVE_GROUPLIST_START: null,
  RECEIVE_GROUPLIST_SUCCESS: null,
  RECEIVE_GROUPLIST_FAILURE: null,
  RECEIVE_GROUP_START: null,
  RECEIVE_GROUP_SUCCESS: null,
  RECEIVE_GROUP_FAILURE: null,
  RECEIVE_ACCESS_LEVELS_START: null,
  RECEIVE_ACCESS_LEVELS_SUCCESS: null,
  RECEIVE_ACCESS_LEVELS_FAILURE: null,
  RECEIVE_INTERN_START: null,
  RECEIVE_INTERN_SUCCESS: null,
  RECEIVE_INTERN_FAILURE: null,
  RECEIVE_INTERNROLES_START: null,
  RECEIVE_INTERNROLES_SUCCESS: null,
  RECEIVE_INTERNROLES_FAILURE: null,
  RECEIVE_ROLES_START: null,
  RECEIVE_ROLES_SUCCESS: null,
  RECEIVE_ROLES_FAILURE: null,
  RECEIVE_UIOCARD_START: null,
  RECEIVE_UIOCARD_SUCCESS: null,
  RECEIVE_UIOCARD_FAILURE: null
})
