export const interns =['interns']
export const groups =['groups']
export const accesslevels =['accesslevels']
export const internList = ['internList']
export const group = ['group']
export const roles = ['roles']
export const internroles = ['internroles']
export const uio_cards = ['uiocards']
