import keyMirror from "fbjs/lib/keyMirror"

export default keyMirror({
  RECEIVE_INVENTORYCOUNTS_START: null,
  RECEIVE_INVENTORYCOUNTS_SUCCESS: null,
  RECEIVE_INVENTORYCOUNTS_FAILURE: null,
  RECEIVE_INVENTORYCOUNT_START: null,
  RECEIVE_INVENTORYCOUNT_SUCCESS: null,
  RECEIVE_INVENTORYCOUNT_FAILURE: null,
  RECEIVE_INVENTORYCOUNTCOUNTS_START: null,
  RECEIVE_INVENTORYCOUNTCOUNTS_SUCCESS: null,
  RECEIVE_INVENTORYCOUNTCOUNTS_FAILURE: null,
  VARE_ADDED: null,
  INVENTORYCOUNT_FILTERS: null,
  INVENTORYCOUNT_FILTERS_CLEAR: null,
})
